### ISSUE TITLE
scad extension not added to generated files

### ISSUE THREAD

**Issue by krankydonkey** [geoffder/dometyl-keyboard#10]
All the base models and incl_ models are being generated, but only as plain files with no extension. This causes dune build @export_models to not work as well (I'm assuming) as it can't detect any .scad files

**Comment by geoffder** [comment]
Thanks for the report. It's been a long time so I can't remember, but I think my helper `to_file` or equivalent used to add the `.scad` on the end to save the repetition. Guess I droppep it along the way cleaning things up. I'll try to push a fix soon, but in the meantime you can just add the extension to the names in `main.ml`.

**Comment by krankydonkey** [comment]
It has been a while hey. I looked at this project a couple of years ago and
really liked it, but couldn't quite get the walls to generate properly.
Getting tired of having all the parts lying around and want to actually
finish it now though 😄

**Comment by geoffder** [comment]
Nice, hope it works out for you this time! I'd like to revisit this and maybe make some improvements while making a new board, but it'll have to wait a bit longer.

**Comment by krankydonkey** [comment]
Hey while I have you here, is there a way to set the wall generator back to
the old straight segments? I think I prefer that aesthetic to the new
rounded one.

**Comment by geoffder** [comment]
Yeap, roundovers on the keyholes (which get swept into walls) are optional.

https://github.com/geoffder/dometyl-keyboard/blob/74671ba6ce1c03f679e8351e3c33ef6008171c63/models/examples/splaytyl.ml#L104

The `~corner` optional argument is a roundover function. If you remove it, the walls will have sharp corners like they used to. You can also do chamfering, I'd you'd prefer that (see skeletyl example).
https://github.com/geoffder/dometyl-keyboard/blob/74671ba6ce1c03f679e8351e3c33ef6008171c63/models/examples/skeletyl.ml#L85

**Comment by krankydonkey** [comment]
I've deleted the ~corner options, and it solves a small section of the
sweep, but I was more talking about the main wall section, which are still
very rounded. I'm trying to get it to look like the ones in the first
picture of the github.

**Comment by geoffder** [comment]
Do you mean the connectors that run along the ground, connecting the walls? There is another `~corner` for those here:
https://github.com/geoffder/dometyl-keyboard/blob/74671ba6ce1c03f679e8351e3c33ef6008171c63/models/examples/splaytyl.ml#L82

Also, you might be wanting to get rid of the fillets, which should be able to be done (sorry don't have time to test) by giving ```~fillet_h:(`Abs 0.)``` in the application of `Connect.skeleton`.

**Comment by krankydonkey** [comment]
Sorry, I should have included an image. I mean these curves. You can see
deleting the ~corner options has changed the little segment on the top
right, but the rest of the connector/wall is still swept.

[image: curve.png]

**Comment by geoffder** [comment]
It seems that the image did not make the trip via email.

**Comment by krankydonkey** [comment]
dang. How about as an attachment

**Comment by geoffder** [comment]
Afraid not. Taking a guess at what it's about though in the mean time:

For the connectors along the ground, splines are the only option now besides joining the whole height of the wall. Playing with the parameters might get some of the angular look you want back though, like turning `~fn` way down (number of points in the spline path). When I was updating I was having trouble coming to a solution for straight connections that I was happy with so I just went with splines (for then, which has lasted until now) since they were less likely to break.
